### ISSUE TITLE
double nodes for macronized versions in dependencies

### ISSUE THREAD

**Issue by wumpz** [jQAssistant/jqa-maven3-plugin#13]
I am using the latest version of JQAssistant within a multimodule maven 3 project.

I have a dependency in one of my modules like:

```xml
<dependency>  
  <groupId>mygroup</groupId>
  <artifactId>configuration.utilities</artifactId>
  <version>${mygroup.version}</version>
</dependency>
```

This property **mygroup.version** has a fixed value of maybe 5.1. 

So after a successfull JQAssistant process without any fancy additional configuration using this Cyper query:

```sql
MATCH (n:Artifact)
WHERE n.fqn starts with 'com.gingko.commons:configuration.utilities'
RETURN n 
```

My problem here is that I nearly for all of my modules I get **two** nodes as an answer. Here is an example derived from the configuration above:

|data
|----
|{"name":"configuration.utilities","fileName":"***/configuration.utilities/${mygroup.version}/configuration.utilities-${mygroup.version}.jar","fqn":"mygroup:configuration.utilities:jar:${mygroup.version}","type":"jar","version":"${mygroup.version}","group":"mygroup"}
|{"name":"configuration.utilities","fileName":"***/configuration.utilities/5.1/configuration.utilities-12.1.12.jar","fqn":"mygroup:configuration.utilities:jar:5.1","type":"jar","version":"5.1","group":"mygroup"}

Within one node the macro is replaced, within the other, it is not.

Is there any reason behind this or is this simply a bug?

**Comment by obfischer** [comment]
Welcome @wumpz to our community,

the Maven 3 Plugin creates to models for a Maven project. One is the normal model and the other is the effective model. The effective model is the POM that results from the application of interpolation, inheritance and active profiles. This is the reason why the first result still contains the property `mygroup.version` while the second result contains the resolved value of the property.

To fix this, you start your query with the node for the Maven project (`project:Maven:Project`) and then follow the outgoing releation ship `-[:HAS_EFFECTIVE_MODEL]->(pom:Pom)`.

**Comment by wumpz** [comment]
So my problem ;). Thx for clarifying that. BTW: Ist das hier auch der richtige Ort, um auch Fragen loszuwerden? Außerdem war ich etwas überrascht, dass hier nur so wenige Issues verwaltet werden. Ist das eigentliche Issuetracking woanders?

Hab nämlich noch viele Fragen. 

Ansonsten: Merry XMas.

**Comment by obfischer** [comment]
Kein Problem, freue mich geholfen zu haben.

Fragen am besten über Stackoverflow und mit jqassistant taggen. 

Frohes Fest!
