### ISSUE TITLE
Improve performance for scan

### ISSUE THREAD

**Issue by StefanPenndorf** [jQAssistant/jqa-maven3-plugin#15]
Unfortunately the scanning of the maven pom takes very long with our multi module project. Currently the scanning takes 1 to 3 seconds for a multi module project with 95 modules. Thus scanning takes between two and three minutes. Performance seemed to degrade slowly over the last months when our project grew.

![image](https://user-images.githubusercontent.com/990538/111998861-b8296d80-8b1c-11eb-8d2c-ce9d5a952db9.png)

The project has about 140.000 LOC.

As you can see from the analysis the problem seems to be the dependency management section. We're using spring-boot-dependencies as a parent which has a huge dependency management section thus I guess this causes the 182.115 calls to `getMavenArtifactDescriptor()`. Unfortunately we cannot exclude the dependency management section from scanning nor exclude the Plugin at all (see https://github.com/jQAssistant/jqa-core-framework/issues/44).

Are there any possibilities to speed up the scanning?

**Comment by DirkMahler** [comment]
Looks like a huge dependency (management) tree that is resolved. This is a known issue in 1.8.x and has been adressed in jQA 1.9.0. Can you check if this still happens with the latest version?

**Comment by StefanPenndorf** [comment]
Switching from 1.8.0 to 1.9.0 reduced scan time by 50%. I though we're on the latest but wasn't. Sorry for not trying to upgrade first. Had no time today to check again with profiler. I'll leave the issue open, if I find some time to investigate with version 1.9.0 whether the same bottle neck exists.

**Comment by StefanPenndorf** [comment]
Scanning is now much faster, closing the issue as the upgrade to 1.9.0 seems to be the solution. Sorry for that false-positive.
