### ISSUE TITLE
Some goals don't run a multi-module project if last module has property `jqassistant.skip` set to true

### ISSUE THREAD

**Issue by murdos** [jQAssistant/jqa-maven3-plugin#18]
### Expected Behaviour

In a multi-module maven project, one might want to skip jqassistant on some modules (e.g. if it contains gatling tests).
However if the last module to run has `jqassistant.skip` property set to `true`, some goals like `jqassistant:analyze` or `jqassistant:server` don't run anymore. NB: `jqassistant:scan` seems to work.

I tested skipping jqassistant on another non final module: maven plugin works as expected.

### Your Environment
- OpenJDK8 or OpenJDK17 (reproduced with both)
- NixOS
- jqassistant-maven-plugin 1.11.1

### How can we reproduce the bug?

Run `mvn jqassistant:server` on https://github.com/murdos/piggymetrics/tree/jqa-playground

### Definition of Done for the Implementers
- [ ] We got a final feedback from the reporting user (_if applicable_)
- [ ] Unittests have been written (_if applicable_)
- [ ] Integration tests have been written (_if applicable_)
- [ ] Test coverage is the same or even better then before (_if applicable_)
- [ ] Documentation has been written (_if applicable_)
- [ ] Added a note on the new feature to the release notes (_if applicable_)

**Comment by StephanPirnbaum** [comment]
Closed with https://github.com/jQAssistant/jqa-maven-plugin/issues/81
